# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Currency_MVVM' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Currency_MVVM
   pod 'RxSwift', '~> 4'
    pod 'RxCocoa', '~> 4'
    pod 'RxAlamofire', '~> 4'
    pod 'SwiftyJSON' , '~> 4'
end
